<div class="container">
    <!--<div class="jumbotron jumbotron-fluid">
         <div class="col-md-9 offset-md-1">
            <h1 class="display-4">Gkult Corp</h1>
            <p class="lead">Em meados de 2017 nasce a Gkult Corp. Com a aprimoração
            de estudos sobre programação para desenvolvimento web e a criação de um framework PHP, houve a necessidade de mostrar quem fazia os sites  e qual 
            empresa estaria por trás. Assim, os sites passaram a ser assinados pela Gkult Corp.</p>
        </div>
    </div>-->
    <div class="container">

        <h1 class="mt-3"><?= $this->getPageTitle(); ?></h1>

        <p>R. Soares, curioso por natureza, sempre procurei aprender coisas que me interessam. Formado em Matemática, especialista em Educação Matemática
            e em Tecnologias para Desenvolvimento Web, não parei por aí.</p>
        <p>Sempre tive interesse na cutelaria e daí ter montado uma pequena oficina para fazer uma ou outra faca por hobby. E neste site mostro
            um pouco do que pesquisei, pus em prática e que realmente acredito, ou seja, o que peguei das melhores fontes de pesquisa. Aqui dou
            ênfase aos "gringos", não porque nosso país não tenha profissonais de renome, ótimos, mas pela quantidade de material que supera muito a nacional.</p>
        <p>Boa parte dos posts <b>não é minha opnião ou conhecimento</b>, basta olhar no final do artigo e verá a fonte, de onde ele foi traduzido ou adptado.</p>

        <p class="text-end">Boa leitura!!!</p>

        <h2 class="h3 text-center my-3">Política de privacidade</h2>
        <p> Versão 05/05/2021</p>

        <p>A proteção de dados é uma questão de confiança, e a proteção de sua privacidade é importante para nós. 
            Ao processar dados pessoais, cumprimos as disposições legais de acordo com a lei nº 13.709, DE 14 DE AGOSTO DE 2018, Lei Geral de Proteção de 
            Dados Pessoais (LGPD).</p>
        <p>
            Se você tiver alguma dúvida ou comentário sobre nossas informações de proteção de dados, entre em contato conosco em: webdesigner@gkult.net.</p>
        <p>
            Como o nosso negócio está em constante atualização, nossa Política de Privacidade também poderá sofrer atualizações. 
            Você deve verificar nosso site com frequência para ver alterações recentes. 
        </p>
        <p>
            Este site coleta apenas as seguintes informações:
        </p>
        <ul>
            <li>Dados básicos de navegação;</li>
            <li>Dados de navegação por app de terceiros: Google Analytics;</li>
            <li>Nome e e-mail, <b>somente</b> ao se cadastrar na página inicial.</li>
        </ul>
        <p>
            Nunca enviamos dados para outras fontes, além do presente site!
        </p>
        <p>
            Não temos uma forma de você desabilitar, via site, o uso de cookies. Mas sinta-se a vontade para desabilitar
            no seu navegador, o que não comprometerá a navegação em nosso site!
        </p>
    </div>
</div>
