    <div class="container">

        <h1 class="mt-3"><?= $this->getPageTitle(); ?></h1>

        <p>Contar um pouco do site</p>

        <h2 class="h3 text-center my-3">Política de privacidade</h2>
        <p> Versão 05/05/2021</p>

        <p>A proteção de dados é uma questão de confiança, e a proteção de sua privacidade é importante para nós. 
            Ao processar dados pessoais, cumprimos as disposições legais de acordo com a lei nº 13.709, DE 14 DE AGOSTO DE 2018, Lei Geral de Proteção de 
            Dados Pessoais (LGPD).</p>
        <p>
            Se você tiver alguma dúvida ou comentário sobre nossas informações de proteção de dados, entre em contato conosco em: webdesigner@gkult.net.</p>
        <p>
            Como o nosso negócio está em constante atualização, nossa Política de Privacidade também poderá sofrer atualizações. 
            Você deve verificar nosso site com frequência para ver alterações recentes. 
        </p>
        <p>
            Este site coleta apenas as seguintes informações:
        </p>
        <ul>
            <li>Dados básicos de navegação;</li>
            <li>Dados de navegação por app de terceiros: Google Analytics;</li>
            <li>Nome e e-mail, <b>somente</b> ao se cadastrar na página inicial.</li>
        </ul>
        <p>
            Nunca enviamos dados para outras fontes, além do presente site!
        </p>
        <p>
            Não temos uma forma de você desabilitar, via site, o uso de cookies. Mas sinta-se a vontade para desabilitar
            no seu navegador, o que não comprometerá a navegação em nosso site!
        </p>
    </div>
