<div class="text-center">
    <h1>Desative o adblock</h1>
    <p>
        Você está usando Adblock Plus ou qualquer outra coisa que bloqueia as Publicidades.<br>
        Desative o Adblock para prosseguir!<br>
        Só podemos existir graças as publicidades.Como todos nossos serviços são gratuitos nós dependemos das publicidades para pagar nossos servidores.<br>
        Por isso pedimos a vocês para permitirem os anúncios na hora de usar o nossos serviços!<br><br>

        <strong>Desabilitando o Adblock:</strong><br>
        <img src="/assets/img/adblock.png" /><br>
        Você só tem que clicar em "Desativar Adblock Plus"<br></p>
</div>
