
<div class="row col-md-10 col-md-offset-1 custyle">
    <div class="page-header">     
        <h2 class="card-title py-3">Visitors by IP</h2>
    </div> 
    <?php if (!empty($this->view->visitor)): ?>
        <table class="table table-striped custab sortable">
            <thead>        
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Id_title</th>
                    <th>IP</th>
                    <th>Acessed in</th>            
                    <th class="text-center">Action</th>
                </tr>
            </thead>    
            <tbody>
                <?php foreach ($this->view->visitor as $vis): ?>                
                    <tr>
                        <td><?= $vis['viId'] ?></td>
                        <td><?= $vis['title'] ?></td> 
                        <td><?= $vis['articles_id'] ?></td> 
                        <td><?= $vis['ip'] ?></td>
                        <td><?= $vis['acessed_in'] ?></td>
                        <td class="text-center">                     
                            <a href="/admin/delete/visitor/<?= $vis['viId'] ?>" class="btn btn-danger btn-xs" 
                               onclick="confirm('Tem certeza que quer excluir?')"><span class="glyphicon glyphicon-remove"></span> Del</a>                         
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?> 
        <p>Não houve visitas!</p>
    <?php endif; ?>

    <!-- Pagination -->
    <?php if ($this->view->contar > 1): ?>
        <ul class="pagination justify-content-center mt-3">
            <?php
            $pag = @$_GET['page'];
            //Tratamento do Previous ou <<
            if (isset($pag)) {
                if ($pag == 1 || $pag == null) {
                    $p = '#';
                } else {
                    $n = $pag - 1;
                    $p = "/admin/show/visitor?page=$n";                    
                }
            }
            ?>     
            <li class="page-item">
                <a class="page-link" href="<?= $p; ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>

            <?php for ($i = 1; $i <= $this->view->contar; $i++): ?>
                <?php if ($i == $this->view->atual): ?> 
                    <li class="page-item active">
                        <a class="page-link" href="#"><?= $i ?></a>
                    </li>  
                <?php else: ?> 
                    <li class="page-item">
                        <a class="page-link" href="/admin/show/visitor?page=<?= $i ?>"><?= $i ?></a>
                    </li>                   
                <?php endif; ?>
            <?php endfor; ?>

            <?php
            //Tratamento do Next ou >>
            if ($pag == $this->view->contar) {
                $p = '#';
            } else {
                if ($pag == null) {
                    $p = "/admin/show/visitor?page=2";
                } else {
                    $n = $pag + 1;
                    $p = "/admin/show/visitor?page=$n";
                }
            }
            ?>
            <li class="page-item">
                <a class="page-link" href="<?= $p; ?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    <?php endif; ?>    
</div>
