<?php if (@$this->view->sucess): ?>
    <div class="alert alert-sucess alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <?php foreach ($this->view->sucess as $msg): ?>
        <p><i class="glyphicon glyphicon-ok-sign"></i> <?= $msg ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>