<div class="page-header">
    <h3 class="h3 py-3"><?= $this->getPageTitle() ?></h3>
</div>   
<form action="/admin/store/article" method="post" enctype="multipart/form-data" accept-charset="utf-8">

    <div class="row">
        <div class="col-lg-8">
            <div class="form-group">
                <label for="title">Título</label>
                <input type="text" name="title" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="image">Imagem de capa</label>
                <input type="text" name="image" class="form-control" placeholder="Ex.: flores.jpg, maria-mole.png">
            </div>
            <div class="form-group">
                <label for="upload">Upload</label>
                <input type="file" name="files[]" class="form-control" multiple id="arquivos">                                   
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label class="control-label" for="categorias">Categorias</label>
                <?php foreach ($this->view->categories as $cat): ?>
                    <div class="radio">
                        <label>
                            <input type="radio" name="categories_id" value="<?= $cat['id'] ?>" required> <?= $cat['name'] ?>
                        </label>
                    </div>
                <?php endforeach; ?>            
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="content">Artigo</label> <i class="fa fa-calendar pull-right"> <?= date('d-M-Y H:i:s'); ?></i>  
        <textarea name="content" class="form-control" rows="15"></textarea>         
    </div>
    <div class="form-group">
        <label for="authors_id">Autores</label>
        <select class="form-control" required name="authors_id">
            <option value="" selected>Authors</option>
            <?php foreach ($this->view->authors as $aut): ?>
                <option value="<?= $aut['id'] ?>"><?= $aut['name'] ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <input type="hidden" name="created" value="<?= date('Y-m-d H:i:s'); ?>">

    <a href="/admin" class="btn btn-danger my-3">Cancelar</a>
    <button type="submit" class="btn btn-primary my-3">Salvar</button>
</form>

