
<h2 class="card-title py-3">Articles</h2>

<p class="text-end"><a href="/admin/create/article" class="btn btn-primary" ><i class="bi bi-pencil-square"></i> Add new articles</a></p>
<?php if (!empty($this->view->articles)): ?>
    <table class="table table-striped custab article-admin sortable">
        <thead>            
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Image</th>
                <th>Category</th>
                <th>Author</th>
                <th>Action</th>
            </tr>
        </thead>
        <?php
        foreach ($this->view->articles as $art):
            $data = ($art['created'] < $art['updated']) ? date("d/m/Y", strtotime($art['updated'])) : date("d/m/Y", strtotime($art['created']));
            $hora = ($art['created'] < $art['updated']) ? date("h:i A", strtotime($art['updated'])) : date("h:i A", strtotime($art['created']))
            ?>
            <tr>
                <td><?= $art['id'] ?></td>
                <td><?= $data . ' -' . $art['title'] ?></td>
                <td><img src="/assets/uploads/articles/thumbs.php?i=<?= $this->helper->urlSEO($art['title'], '-') . '/' . $art['image'] ?>&w=80&h=40"></td>
                <td><?= $art['caName'] ?></td>
                <td><?= $art['auName'] ?></td>
                <td>
                    <a class='btn btn-success btn-sm' href="/admin/preview/<?= $art['id'] ?>" target="_blank"><i class="fa fa-eye"></i> Preview</a> 
                    <a class='btn btn-info btn-sm' href="/admin/edit/article/<?= $art['id'] ?>"><span class="fa fa-pencil-square-o"></span> Edit</a> 
                    <a href="/admin/delete/article/<?= $art['id'] ?>" class="btn btn-danger btn-sm" 
                       onclick="confirm('Tem certeza que quer excluir?')"><i class="fa fa-trash-o"></i> Del</a>
                    <a href="/admin/approve/articles/<?= $art['id'] ?>" class="btn btn-warning btn-sm">
                        <span class="fa fa-thumbs-o-<?php echo ($art['status'] == "yes") ? 'up' : 'down' ?> "></span> <?php echo ($art['status'] == "yes") ? 'Approve' : 'Disapprove' ?> </a>      
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?> 
    <p>Não há artigos a listar!!</p>
<?php endif; ?>

<!-- Pagination -->
<?php if ($this->view->contar > 1): ?>
    <ul class="pagination justify-content-center mt-3">
        <?php
        $pag = @$_GET['page'];
        //Tratamento do Previous ou <<
        if (isset($pag)) {
            if ($pag == 1 || $pag == null) {
                $p = '#';
            } else {
                $n = $pag - 1;
                $p = "/admin?page=$n";
            }
        }
        ?>     
        <li class="page-item">
            <a class="page-link" href="<?= $p; ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        <?php for ($i = 1; $i <= $this->view->contar; $i++): ?>
            <?php if ($i == $this->view->atual): ?> 
                <li class="page-item active">
                    <a class="page-link" href="#"><?= $i ?></a>
                </li>  
            <?php else: ?> 
                <li class="page-item">
                    <a class="page-link" href="/admin?page=<?= $i ?>"><?= $i ?></a>
                </li>                   
            <?php endif; ?>
        <?php endfor; ?>

        <?php
        //Tratamento do Next ou >>
        if ($pag == $this->view->contar) {
            $p = '#';
        } else {
            if ($pag == null) {
                $p = "/admin?page=2";
            } else {
                $n = $pag + 1;
                $p = "/admin?page=$n";
            }
        }
        ?>
        <li class="page-item">
            <a class="page-link" href="<?= $p; ?>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
<?php endif; ?>    




