
<div class="page-header">
    <h3 class="h3"><?= $this->getPageTitle() ?></h3>
</div>  

<form action="/admin/store/category" method="post" accept-charset="utf-8">
    <div class="row justify-content-center">
        <div class="col-10">
            <div class="col-8">
                <div class="form-group">
                    <label for="title">Name</label>
                    <input type="text" name="name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="slug">Slug</label>
                    <input type="text" name="slug" class="form-control">
                </div>
                <div class="form-group">
                    <label for="description">Description:</label>    
                    <textarea name="description" class="form-control" rows="10"></textarea>         
                </div>            

                <a href="/admin" class="btn btn-danger">Cancelar</a>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </div>
</form>
</div>
