
<h2 class="card-title separator">Categories</h2>
 
    <p class="text-right"><a href="/admin/create/category" class="btn btn-primary" ><i class="fa fa-pencil"></i> Add new categories</a></p>
    <?php if (!empty($this->view->categories)): ?>    
        <table class="table table-striped custab sortable">
            <thead>
            
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Slug</th>
                <th>Description</th>
                <th class="text-center">Action</th>
            </tr>
            </thead>     
            <?php foreach ($this->view->categories as $cat): ?>
                <tr>
                    <td><?= $cat['id'] ?></td>
                    <td><?= $cat['name'] ?></td>
                    <td><?= $cat['slug'] ?></td>
                    <td><?= $cat['description'] ?></td>
                    <td class="text-center" width="20%">
                        <a class='btn btn-info btn-xs' href="/admin/edit/category/<?= $cat['id'] ?>"><span class="fa fa-pencil-square-o"></span> Edit</a> 
                        <a href="/admin/delete/category/<?= $cat['id'] ?>" class="btn btn-danger btn-xs" 
                           onclick="confirm('Tem certeza que quer excluir?')"><span class="fa fa-trash-o"></span> Del</a>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?> 
        <p>Não há categorias a listar!!</p>       
    <?php endif; ?>
    <?php if ($this->view->contar > 1): ?>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="disabled">&laquo;</span>
                    </a>
                </li>
                <?php
                for ($i = 1; $i <= $this->view->contar; $i++) {
                    if ($i == $this->view->atual) {
                        echo '<li class="active"><a href="#">' . $i . ' <span class="sr-only">(current)</span></a></li>';
                    } else {
                        echo '<li><a href="/admin/show/category?page=' . $i . '">' . $i . ' </a></li>';
                    }
                }
                ?>         
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="disabled">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    <?php endif; ?>