<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $this->getPageTitle('|') . $this->getSiteName() ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="follow, index" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@200;300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/custom_web.css">
        <link rel="shortcut icon" href="/assets/img/favicon_lscutelaria.ico" />
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
        <?php // require_once "../storage/marketing/ga-lscutelaria.inc" ?>
        <?php // require_once "../storage/marketing/adsense-lscutelaria.inc" ?>
            </head>
    <body>        
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container">
                    <img src="/assets/img/logo.png" class="img-logo"> 
                    <a class="navbar-brand" href="/"><?= $this->getSiteName() ?></a>                
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" 
                            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse ml-auto" id="navbarResponsive">
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item pl-5">
                                <a class="nav-link" href="/">Home</a>
                            </li>
                            <li class="nav-item pl-5">
                                <a class="nav-link" href="/articles">Blog</a>
                            </li>
                            <li class="nav-item pl-5">
                                <a class="nav-link" href="/about">Sobre</a>
                            </li>
                            <li class="nav-item pl-5">
                                <a class="nav-link" href="/contact">Contato</a>
                            </li>                  
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <?php $this->content(); ?>  

        <!--Back totop-->
        <button type="button" class="btn btn-small btn-danger top" data-toggle="tooltip"><i class="fa fa-chevron-up"></i></button>
        <!--end totop-->

        <!-- Footer -->
        <footer class="py-4 bg-light">
            <div class="container">
                <p class="m-0 text-center text-dark">&copy;Copyright <b><?= $this->getSiteName() ?></b> -  2021<br>
                    by <span id="signature">R. Soares</span></p>
            </div>    
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>  
        <script src="/assets/js/maskbrphone.js" type="text/javascript"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
        <script src="/assets/js/myJSfunctions.js" type="text/javascript"></script>       
    </body>
</html>
