<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login | <?= $this->getSiteName() ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="nofollow, noindex" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@200;300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/custom_web.css">
        <link rel="shortcut icon" href="/assets/img/favicon_lscutelaria.ico" />
    </head>
    <body> 
        <div class="container-fluid">
            <div class="admin py-1">                
                <img src="/assets/img/banner_admin_login.jpg" alt="" class="img-fluid w-100"/>              
            </div>  
            <hr>
        </div>

        <div class="container">
            <?php $this->content(); ?>
        </div>       

        <!--Back totop-->
        <button type="button" class="btn btn-lg btn-warning top" data-toggle="tooltip"><i class="fa fa-chevron-up"></i></button>
        <!--end totop-->

        <footer class="py-4 bg-light">
            <div class="container">
                <p class="m-0 text-center text-dark">&copy;Copyright <b><?= $this->getSiteName() ?></b> -  2021<br>
                    by <span id="signature">R. Soares</span></p>
            </div>    
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>  
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.5.6/tinymce.min.js"></script>
        <script src="/assets/js/sorttable.js" type="text/javascript"></script>
        <script src="/assets/js/tinymce_config.js"></script>

    </body>
</html>