<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $this->getPageTitle('|') . $this->getSiteName() ?></title> 
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="nofollow, noindex" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@200;300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/custom_web.css">
        <link rel="shortcut icon" href="/assets/img/favicon_lscutelaria.ico" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
                <div class="container">
                    <a class="navbar-brand" href="/"><?= $this->getSiteName(); ?></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">

                            <li class="nav-item active">
                                <a class="nav-link" href="/admin">Voltar
                                    <span class="sr-only">(current)</span>
                                </a>
                            </li>                      
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        
        <?php $this->content(); ?>

        <!--Back totop-->
        <button type="button" class="btn btn-lg btn-warning top" data-toggle="tooltip"><i class="fa fa-chevron-up"></i></button>
        <!--end totop-->

        <div class="footer-bottom">
            <div class="container">
                <p class="pull-left"> Copyright © <?= $this->getSiteName(); ?>. All right reserved. </p>               
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>      
    </body>
</html>
