<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Área Administrativa | <?= $this->getSiteName() ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="nofollow, noindex" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@200;300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/custom_web.css">
        <link rel="shortcut icon" href="/assets/img/favicon_lscutelaria.ico" />
    </head>
    <body>        
        <div class="container-fluid">
            <div class="admin py-1">                
                <img src="/assets/img/banner_admin_login.jpg" alt="" class="img-fluid w-100"/>              
            </div>  
            <hr>
        </div>

        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark text-light bg-dark">
                <div class="container">
                    <a class="navbar-brand" href="/" target="_blank"><?= $this->getSiteName() ?></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="/admin">Home <span class="sr-only">(current)</span></a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Actions
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="/admin/show/article">Articles</a></li>
                                    <li><a class="dropdown-item" href="/admin/show/author">Authors</a></li>
                                    <li><a class="dropdown-item" href="/admin/show/category">Categories</a></li>
                                    <li><a class="dropdown-item" href="/admin/show/visitor">Visitors</a></li>
                                    <li><a class="dropdown-item" href="/admin/show/newsletter">Newsletter</a></li>

                                </ul>                              
                            </li>                       
                        </ul>
                    </div>
                    <?php if ($this->auth->check()): ?>
                        <div class="collapse navbar-collapse" id="navbarResponsive">
                            <ul class="navbar-nav pull-right">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="fa fa-user"></i> <?php echo $this->auth->name() ?> 
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="/logout"><i class="bi bi-box-arrow-right"></i> Logout</a> </li>
                                    </ul>                                  
                                </li>                    
                            </ul>
                        </div>
                    <?php endif; ?>
                </div>
            </nav>
        </div>

        <div class="container">
            <?php $this->content(); ?>
        </div>

        <!--Back totop-->
        <button type="button" class="btn btn-lg btn-warning top" data-toggle="tooltip"><i class="fa fa-chevron-up"></i></button>
        <!--end totop-->

        <footer class="py-4 bg-light">
            <div class="container">
                <p class="m-0 text-center text-dark">&copy;Copyright <b><?= $this->getSiteName() ?></b> -  2021<br>
                    by <span id="signature">R. Soares</span></p>
            </div>    
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>  
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.5.6/tinymce.min.js"></script>
        <script src="/assets/js/sorttable.js" type="text/javascript"></script>
        <script src="/assets/js/tinymce_config.js"></script>
    </body>
</html>
